### ISSUE TITLE
/usr/local/bin/pmacct-to-elasticsearch: Permission denied

### ISSUE THREAD

**Issue by hyperopticadam** [pierky/pmacct-to-elasticsearch#7] opened 2017-07-04 15:38 UTC
Hi Guys, 

When I try to run sfacctd -f /some/conf/file with a trigger I get

/etc/p2es/triggers/plugin2: 21: /etc/p2es/triggers/plugin2: /usr/local/bin/pmacct-to-elasticsearch: Permission denied

Config file
-
plugins: memory[plugin1], print[plugin2]

print_output_file[plugin2]: /var/lib/pmacct/plugin2.json
print_output[plugin2]: json
print_trigger_exec[plugin2]: /etc/p2es/triggers/plugin2
print_refresh_time[plugin2]: 60
aggregate[plugin2]: proto,src_port

Trigger
-
{
    "ES_URL": "http://10.255.28.199:9200",
    "ES_IndexName": "example-%Y-%m-%d",
    "ES_Type": "source_port",
    "InputFile": "/var/lib/pmacct/plugin2.json",
}

Any help would be greatly appreciated.

Thanks 

Adam

**Comment by pierky** [comment] 2017-07-04 16:14
Hello, did you try to give execution rights on /usr/local/bin/pmacct-to-elasticsearch to the user that you use to run sfacctd?

**Comment by hyperopticadam** [comment] 2017-07-04 16:19
Hello Pier,

Yes we did, and we run the sfacctd command as sudo.

We are running the latest vertion of pmacct.

Thanks

Adam

**Comment by pierky** [comment] 2017-07-05 17:14
Hello,

I've just tested a brand new deployment on a Debian 8 (jessie) Docker container using pmacctd 1.7.0-git (20170705-00) (master from GitHub) and I've got no problems using your configuration.

Just one note about the trigger JSON configuration file: you need to remove the comma at the end of the last line:

```
"InputFile": "/var/lib/pmacct/plugin2.json",

                                           ^
```

Since I have not been able to reproduce your issue, I can suggest you to double check permissions on Python binaries, triggers and on the /usr/local/bin/pmacct-to-elasticsearch file.

If it's ok for you, I could take a look at your setup if you can give me access to your environment. In that case please contact me privately for details: https://pierky.com/#contactme

Thanks

**Comment by pierky** [comment] 2017-07-20 16:50
Hello @hyperopticadam,

did you manage to solve this problem? I didn't hear back from you, I tentatively close this issue but please feel free to reopen it or to contact me privately.

**Closed as completed by pierky** 2017-07-20 16:50 UTC

**Comment by hyperopticadam** [comment] 2017-07-20 17:30
Hi!

Yes sorry it was a permission issue so was user incompetence!

Thanks for the help though and apologies I forgot to reply

Sent from my iPhone

On 20 Jul 2017, at 17:51, Pier Carlo Chiodi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @hyperopticadam<https://github.com/hyperopticadam>,

did you manage to solve this problem? I didn't hear back from you, I tentatively close this issue but please feel free to reopen it or to contact me privately.
